import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/component/Footer";
import { Slide, ToastContainer } from "react-toastify";

import Navbar from "@/component/Navbar";
import { ThemeProviderWrapper } from "@/component/ThemeProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "SportNest Booking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="">
        <ThemeProviderWrapper>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </ThemeProviderWrapper>
        <ToastContainer
          position="top-center"
          autoClose={1000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Slide}
        />
      </body>
    </html>
  );
}
